{{- if .Values.application.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  {{- with (mergeOverwrite (deepCopy .Values.global.deploymentAnnotations) .Values.application.deploymentAnnotations) }}
  annotations:
    {{- range $key, $value := . }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
  {{- end }}
  labels:
    {{- include "application.standardLabels" . | nindent 4 }}
  name: {{ include "application.fullname" . }}
  namespace: {{ include  "application.namespace" . }}
spec:
  {{- with (mergeOverwrite (deepCopy .Values.global.deploymentStrategy) .Values.application.deploymentStrategy) }}
  strategy:
    {{- trim . | nindent 4 }}
  {{- end }}
  {{- if not .Values.application.autoscaling.enabled }}
  replicas: {{ .Values.application.replicaCount }}
  {{- end }}
  revisionHistoryLimit: {{ .Values.global.revisionHistoryLimit }}
  selector:
    matchLabels:
      {{- include "application.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.application.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "application.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.application.imagePullSecrets | default .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "application.serviceAccountName" . }}
      {{- with .Values.global.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Values.application.name }}
          {{- with .Values.application.containerSecurityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          image: {{ default .Values.global.image.repository .Values.application.image.repository }}:{{ default .Values.global.image.tag .Values.application.image.tag }}
          imagePullPolicy: {{ default .Values.global.image.imagePullPolicy .Values.application.image.imagePullPolicy }}
          ports:
            - name: {{ .Values.application.containerPortName }}
              containerPort: {{ .Values.application.containerPort }}
              protocol: TCP
          resources:
            {{- toYaml .Values.application.resources | nindent 12 }}
          env:
            {{- with (concat .Values.global.env .Values.application.env) }}
              {{- toYaml . | nindent 12 }}
            {{- end }}
      {{- with .Values.application.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.application.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.application.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}