{{- if and .Values.application.enabled .Values.application.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
automountServiceAccountToken: {{ .Values.application.serviceAccount.automountServiceAccountToken }}
metadata:
  {{- with .Values.application.serviceAccount.annotations }}
  annotations:
    {{- range $key, $value := . }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
  {{- end }}
  labels:
    {{- include "application.standardLabels" . | nindent 4 }}
    {{- with .Values.application.serviceAccount.labels }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
  name: {{ include "application.serviceAccountName" . }}
  namespace: {{ include  "application.namespace" . }}
{{- end }}