{{- if .Values.backend.enabled }}
{{- $global := .Values.global -}}
{{- $instance := .Values.backend -}}
{{- $instanceName := $instance.name -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  {{- include "base.metadata" (dict "context" $ "global" $global "instanceName" $instanceName "instance" $instance ) | nindent 2 }}
spec:
  {{- include "base.deploymentSpec" (dict "context" $ "global" $global "instance" $instance "instanceName" $instanceName ) | indent 2 }}
  template:
    metadata:
      annotations:
      {{- with (mergeOverwrite (deepCopy $global.podAnnotations) $instance.podAnnotations) }}
      {{- range $key, $value := . }}
        {{ $key }}: {{ $value | quote }}
      {{- end }}
      {{- end }}
      labels:
        {{- include "base.selectorLabels" (dict "context" $ "instanceName" $instanceName) | nindent 8 }}
      {{- with (mergeOverwrite (deepCopy $global.podLabels) $instance.podLabels) }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      {{- include "base.podSpec" (dict "context" $ "global" $global "instance" $instance) | indent 6 }}
      containers:
        {{- include "base.container" (dict "global" $global "instanceName" $instanceName "instance" $instance ) | nindent 8 }}
      {{- if $instance.extraContainers }}
        {{- tpl (toYaml $instance.extraContainers ) $ | nindent 8 }}
      {{- end }}
      {{- if $instance.initContainers }}
      initContainers:
        {{- tpl (toYaml $instance.initContainers ) $ | nindent 8 }}
      {{- end }}
{{- end -}}