{{- if and .Values.backend.enabled .Values.backend.serviceAccount.create }}
{{- $global := .Values.global -}}
{{- $instance := .Values.backend.serviceAccount -}}
{{- $instanceName := .Values.backend.name -}}
apiVersion: v1
kind: ServiceAccount
automountServiceAccountToken: {{ $instance.automountServiceAccountToken }}
metadata:
  {{- include "base.metadata.serviceAccount" (dict "context" $ "global" $global "instanceName" $instanceName "instance" $instance ) | nindent 2 }}
{{- end }}