{{- if and .Values.nginx.enabled .Values.nginx.config.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-nginx-config
  labels:
    {{- include "laravel.labels" . | nindent 4 }}
data:
  nginx.conf: |
{{ .Files.Get "files/nginx/nginx.conf" | indent 4 }}
{{- end }}