apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "laravel.fullname" . }}-fpm-conf
  labels:
    {{- include "laravel.labels" . | nindent 4 }}
data:
  php-fpm.conf: |
{{- if .Values.laravel.fpm }}
  {{ .Values.laravel.fpm  | indent 4 }}
{{- end }}
