apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "aspnet.fullname" . }}
  labels:
    {{- include "aspnet.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  {{- with .Values.updateStrategy }}
  strategy:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "aspnet.selectorLabels" . | nindent 6 }}
  {{- with .Values.minReadySeconds }}
  minReadySeconds: {{ . }}
  {{- end }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "aspnet.selectorLabels" . | nindent 8 }}
    spec:
      {{- include "aspnet.pod" . | nindent 6 }}